/* This file is automatically generated; do not edit.     */
/* Add the files to be included into Makefile.am instead. */

#include <ql/qle/instruments/crossccybasisswap.hpp>
#include <ql/qle/instruments/crossccyswap.hpp>
#include <ql/qle/instruments/currencyswap.hpp>
#include <ql/qle/instruments/fxforward.hpp>
