/* This file is automatically generated; do not edit.     */
/* Add the files to be included into Makefile.am instead. */

//#include <qle/pricingengines/analyticcclgmfxoptionengine.hpp>
//#include <qle/pricingengines/analyticlgmswaptionengine.hpp>
#include <ql/qle/pricingengines/crossccyswapengine.hpp>
#include <ql/qle/pricingengines/discountingcurrencyswapengine.hpp>
#include <ql/qle/pricingengines/discountingfxforwardengine.hpp>
#include <ql/qle/pricingengines/discountingswapenginemulticurve.hpp>
//#include <qle/pricingengines/oiccbasisswapengine.hpp>
//#include <qle/pricingengines/numericlgmswaptionengine.hpp>
